### PR TITLE
feat: support for subsets in .meta project file

### PR DESCRIPTION
**Pull request by smileatom**
Support for nesting .meta projects in subsets

explainer/demo - https://vimeo.com/523541918 

image

usage:

include all: `meta exec "ls -la"`
or apps only: `meta exec "ls -la" --subsets /apps`
or just the web apps and services: `meta exec "ls -la" --subsets /apps/web,/services`

### CODE REVIEW

**Comment by mateodelnorte** [comment]
Hi @smileatom. This is something that @patrickleet has wanted for some time. At first glance things look great. I would like to suggest a noun other than subsets, though. Perhaps 'keys', 'groups', or 'sets'? 

Also, loop already has a notion of --include-only and --exclude. Though, I'm not against keeping this short with `--keys=`. 

@patrickleet thoughts? 

Long term, it would be great if meta-loop would check for the existence of child .meta files, combine the graphs, and make them all searchable via `--keys` from the top level.

**Comment by smileatom** [comment]
> Hi @smileatom. This is something that @patrickleet has wanted for some time. At first glance things look great. I would like to suggest a noun other than subsets, though. Perhaps 'keys', 'groups', or 'sets'?
> 
> Also, loop already has a notion of --include-only and --exclude. Though, I'm not against keeping this short with `--keys=`.
> 
> @patrickleet thoughts?
> 
> Long term, it would be great if meta-loop would check for the existence of child .meta files, combine the graphs, and make them all searchable via `--keys` from the top level.

@mateodelnorte I kind of like 'sets', although Im not averse entirely to 'keys', although its a bit javascript-ish.  Sets also allows for 'supersets' which these also can be when nested multiple levels.

**Comment by patrickleet** [comment]
Thanks for the PR! Nice idea on making the video to go with it.

I have wanted something like this and so have others, I was just fine with the workaround so never got to it:
https://github.com/mateodelnorte/meta/issues/234
https://github.com/mateodelnorte/meta/issues/219 (you)
https://github.com/mateodelnorte/meta/issues/112 (I had suggested "tags" here but hadn't considered a nested structure)

`meta` currently supports using subdirectories, and I wonder if that would cause issues using `/` for parsing:

For example:

```
meta project import modules/something git@github.com/org/something
meta project import apps/www git@github.com/org/www
```

Which results in a meta file like:

```
{
  "modules/something": "git@github.com/org/something",
  "apps/www": "git@github.com/org/www"
}
```

Maybe that's ok, and that's a breaking change? 

I know I have plenty of meta repos that use subdirectories like that though.

Maybe `.` would be better? It would also match the fact that you are selecting out of a json structure, and would match formatting used by tools like `jq`. 

Definitely will need to include some doc updates as well about usage in the README.

**Comment by patrickleet** [comment]
Also, for that matter, how are `meta project import` and `meta project create` affected?

**Comment by smileatom** [comment]
Patrick, 

This is something that should be tested.  I added the additional structure by hand in the .meta file.  It would be interesting to run project import and create on a .meta file that has been modified like this to see if it breaks.

Thanks,
Bill

**Comment by smileatom** [comment]
> Thanks for the PR! Nice idea on making the video to go with it.
> 
> I have wanted something like this and so have others, I was just fine with the workaround so never got to it:
> [mateodelnorte/meta#234](https://github.com/mateodelnorte/meta/issues/234)
> [mateodelnorte/meta#219](https://github.com/mateodelnorte/meta/issues/219) (you)
> [mateodelnorte/meta#112](https://github.com/mateodelnorte/meta/issues/112) (I had suggested "tags" here but hadn't considered a nested structure)
> 
> `meta` currently supports using subdirectories, and I wonder if that would cause issues using `/` for parsing:
> 
> For example:
> 
> ```
> meta project import modules/something git@github.com/org/something
> meta project import apps/www git@github.com/org/www
> ```
> 
> Which results in a meta file like:
> 
> ```
> {
>   "modules/something": "git@github.com/org/something",
>   "apps/www": "git@github.com/org/www"
> }
> ```
> 
> Maybe that's ok, and that's a breaking change?
> 
> I know I have plenty of meta repos that use subdirectories like that though.
> 
> Maybe `.` would be better? It would also match the fact that you are selecting out of a json structure, and would match formatting used by tools like `jq`.
> 
> Definitely will need to include some doc updates as well about usage in the README.

Patrick, I updated my other comment but GH lost it.  The --subsets only extend to objects in the .meta file.  You cant extend a subset down to an individual project so slashes in directory paths are unseen by the --subsets option.  

`{
     "projects": {
           "apps": {
                "www": {
                       "apps/www": "github.git"
                 }
           }
     }
}`

The above is fine because --subsets /apps/www  only refers to objects, while the actual project "apps/www" is a string attribute and will not be seen by --subsets only returned as an included directory.

**Comment by mateodelnorte** [comment]
> Also, for that matter, how are `meta project import` and `meta project create` affected?

@patrickleet  Honestly, I think we should deprecate `meta project import` and `meta project add/create` and just have people code the .meta file by hand. 

@smileatom we do need to support the following: 

```
{
  "modules/something": "git@github.com/org/something",
  "apps/www": "git@github.com/org/www"
}
```
So, in the context of your pr, it might be something like:
```
{
  "modules/somethings": {
    "something": "git@github.com/org/something"  
},
  "apps/www": "git@github.com/org/www"
}
```
That would result in a directory structure like: 
```
apps/
  www/
modules/
  somethings/
    something/
```

**Comment by smileatom** [comment]
> > Also, for that matter, how are `meta project import` and `meta project create` affected?
> 
> @patrickleet Honestly, I think we should deprecate `meta project import` and `meta project add/create` and just have people code the .meta file by hand.
> 
> @smileatom we do need to support the following:
> 
> ```
> {
>   "modules/something": "git@github.com/org/something",
>   "apps/www": "git@github.com/org/www"
> }
> ```
> 
> So, in the context of your pr, it might be something like:
> 
> ```
> {
>   "modules/somethings": {
>     "something": "git@github.com/org/something"  
> },
>   "apps/www": "git@github.com/org/www"
> }
> ```
> 
> That would result in a directory structure like:
> 
> ```
> apps/
>   www/
> modules/
>   somethings/
>     something/
> ```

{
>   "modules/somethings": {
>     "something": "git@github.com/org/something"  
> },

So subsets are not physical directories right.  Which is why they dont have slashes because they are structural in nature.  If there is a physical directory involved, it should still be in the string key:
"modules/something": "git...."

subsets are logical groupings which are nested and delimited by '/'

**Comment by mateodelnorte** [comment]
@smileatom do you mean it would be the following? 
```
{
"modules": {
  "somethings": {
    "modules/somethings/something": "git..."
    }
  }
}
```
The point is that the key above is passed to `git clone [deep folder name] remote-url`.

**Comment by smileatom** [comment]
> @smileatom do you mean it would be the following?
> 
> ```
> {
> "modules": {
>   "somethings": {
>     "modules/somethings/something": "git..."
>     }
>   }
> }
> ```
> 
> The point is that the key above is passed to `git clone [deep folder name] remote-url`.

You could do that no problem.  I am working on the git clone right now to support the nesting since it uses Object.keys(project).  Will update the PR on meta-git soon.

**Comment by smileatom** [comment]
A little status:  I have submitted PRs for meta-npm, meta-yarn, symlink-dependencies and meta-git because I found these in the "included plugins" when I did a meta-git clone of the meta project.  I have no idea how many other plugins maybe using Object.keys(projects) although I could search all the meta repos under mateodelnorte if thats needed.

I replaced Object.keys(project) with the recursive search to simply not break anything (in these plugins) if there is nesting in the .meta file.

I did not add support for --subsets to these plugins, I only fixed up the project iteration so things wouldnt break in the case of nesting in the .meta.

So currently the command meta loop and I guess meta exec supports filtering on --subsets which we can change to --sets and add the option -s for a short name I guess.

Other plugins would have to pass through --subsets either to the module call metaLoop( or in the case they are not calling metaLoop, either call the bin/meta-loop or if they dont call meta loop at all they would need to parse --subsets and filter internally if thats an appropriate option.  It seems that in the meta-git case its intended to operate on the full set of projects.  Ill leave that up to the maintainers to decide.

**Comment by smileatom** [comment]
A post clean up task would be to create a lib which would encapsulate recursiveSearch() and also subset filtering to remove the dupe code from the plugins and help plugin writers to reuse the code without copy  pasta

**Comment by smileatom** [comment]
So unfortunately I have to close this PR, mostly because theres a smell here.  The smell is you (supposedly project owners) who (wrote this code?)  Didnt really understand the PR and that it was *your* job to approve or deny the idea, and then look for dependent issues, and then guide a fully fledged solution to the various issues created by this.

So when I see this, by looking at git activity per person.  And I see ownership issues, and lack of interest, I assume a few things.

Project is perhaps "abandoned", project is possibly "stolen code", or project was a luck of the draw from a non programmer reading from a book.

This project is clearly a mix of a couple things.  Its abandoned and run by javascript programmers who may not be the most experienced.

So Im closing this, because I dont work for you, and also if I really need the feature I can rewrite this whole project in a day.
Try being genuine.

**Comment by patrickleet** [comment]
Yo Matt, tell Elon to stop working you so hard - don't you know that @smileatom has important things here?

**Comment by mateodelnorte** [comment]
Hi there. Nobody suggested you work for us. We don't work for you either, so sorry you had the expectation that we'd be immediately available to service your request. Also sorry the intention you expressed in your PR did not map well into the long term intention of the project. 

No stolen code here. Feel free to use something else if you find something else works better. 

But since you did get a bit emotional and decided to make personal comments, I'll make a personal recommendation to you: Try to assume less.

**Pull request closed without merging**
